### ISSUE TITLE
Assistance with Discord Bot for Reset Alerts and Countdown

### ISSUE THREAD

**Issue by mukundkumra** [NathanLithia/genshin.py#1]
Hi Nathan,

I came across your repository while searching for a Discord bot that could notify users when the server, Imaginarium Theatre, and Spiral Abyss reset. Additionally, I’m looking for functionality that displays a dynamic countdown for my Discord server.

It seems your project aligns closely with what I’m looking to implement. If your bot is already functional, could you kindly guide me through setting it up in my server? I’d also love to customize it to better suit my needs.

I wanted to discuss this with you directly but couldn’t find a way to reach out, so I’m hoping you see this message.

Looking forward to your response.

Best regards,
Mukund
mukundkumra621@gmail.com

**Comment by NathanLithia** [comment]
This was just a little project between my friends and I to announce in our discord server when the US servers reset and DM us reminders :)

Unfortunately i am very busy these days and i cant give my projects the full attention that i want to but you are more than welcome to clone the source code for personal use.

if you are not aware on how discord.py works the code is loaded into a discord.py bot like this:
https://discordpy.readthedocs.io/en/stable/ext/commands/cogs.html

except my self.bot is self.client instead if you run into issues loading it.

Good luck!

**Comment by NathanLithia** [comment]
Oh i also forgot to mention you can track Imaginarium Theatre and Spiral Abyss resets at this website, https://paimon.moe/timeline

**Comment by mukundkumra** [comment]
Hi Nathan,

Thank you for your assistance and for sharing the details. I’ll look into building this using your code as a starting point when I have some time. If I run into any issues, I hope you won’t mind if I reach out in the comments or issues section.

Additionally, I’d be very interested in hearing from you if you ever decide to continue working on this project or something similar in this regard. Wishing you all the best with your busy schedule, and thank you again for your help!

Have a great day.

Best regards,
Mukund
mukundkumra621@gmail.com
